---
version: "2"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=gcholette.com
      - SUBDOMAINS=
      - VALIDATION=http
      - EMAIL=gcholette.com #optional
      - DHLEVEL=2048 #optional
    volumes:
      - ./public/:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
